// 完整的 YYC³ 项目数据 - 由 AI 助手生成
// 生成时间: 2026-07-02
// 数据来源: YYC3.html 书签 + GitHub 仓库匹配

const projects = [
  // ===== AI 应用 =====
  {
    id: 1,
    title: "YYC³ 言语Cloud UI",
    description: "UI 组件库与设计系统，统一的视觉规范与高效的界面开发工具",
    imageUrl: "/Project-Screenshot/YYC3-01.png",
    category: "创意设计",
    demoUrl: "https://design-ui.yyc3.top/",
    liveUrl: "https://github.com/YYC-Cube/YYC3-UI-Design-System",
  },
  {
    id: 2,
    title: "言语云量化分析交易系统",
    description: "AI 驱动的金融分析与量化交易系统，智能决策支持平台",
    imageUrl: "/Project-Screenshot/YYC3-02.png",
    category: "金融科技",
    demoUrl: "https://trading.yyc3.vip/",
    liveUrl: "https://github.com/YYC-Cube/YYC3-Financial-Quantitative-Trading-System",
  },
  {
    id: 3,
    title: "YYC³ AI Family",
    description: "AI 驱动的智能编程助手，多 Agent 协作平台，言启象限 · 语枢未来",
    imageUrl: "/Project-Screenshot/YYC3-03.png",
    category: "AI应用",
    demoUrl: "https://ai-family.yyc3.top/",
    liveUrl: "https://github.com/YYC-Cube/YYC3-AI-Family-Multi-Agent-Platform-",
  },
  {
    id: 4,
    title: "YYC³ Portal",
    description: "言启象限 · 语枢未来，统一入口与导航平台，智能应用门户",
    imageUrl: "/Project-Screenshot/YYC3-04.png",
    category: "Web应用",
    demoUrl: "https://portal.yyc3.top/",
    liveUrl: "https://github.com/YYC-Cube/YYC3-Nexus-Portal",
  },
  {
    id: 5,
    title: "智慧社区服务平台",
    description: "Smart City 智慧社区，智能化社区管理与服务，构建未来城市",
    imageUrl: "/Project-Screenshot/YYC3-05.png",
    category: "行业解决方案",
    demoUrl: "https://smart-city.yyc3.top/",
    liveUrl: "https://github.com/YYC-Cube/YYC3-Smart-City-Platform",
  },
  {
    id: 6,
    title: "YYC³ Learning",
    description: "YanYu Smart Cloud³ Learning Platform - 言枢象限·语启未来，智能化在线学习平台",
    imageUrl: "/Project-Screenshot/YYC3-06.png",
    category: "教育科技",
    demoUrl: "https://learning.yyc3.top/",
    liveUrl: "https://github.com/YYC-Cube/YYC3_Learning-Platform",
  },
  {
    id: 7,
    title: "YYC³ AI 智能开发环境",
    description: "AI-PAI 智能开发环境，集成化 AI 开发工具链，提升开发效率",
    imageUrl: "/Project-Screenshot/YYC3-07.png",
    category: "开发工具",
    demoUrl: "https://ai-pai.yyc3.vip/",
    liveUrl: "https://github.com/YYC-Cube/YYC3-AI-PAI",
  },
  {
    id: 8,
    title: "Family AI",
    description: "YYC3 Family AI - 智能编程助手，AI 驱动的代助手与协作平台",
    imageUrl: "/Project-Screenshot/YYC3-08.png",
    category: "AI应用",
    demoUrl: "https://family-ai.yyc3.vip/",
    liveUrl: "https://github.com/YYC-Cube/YYC3-AI-Family",
  },
  {
    id: 9,
    title: "YYC³ AI Family Docs",
    description: "YYC³ AI Family 文档中心，API 文档、使用指南与最佳实践",
    imageUrl: "/Project-Screenshot/YYC3-09.png",
    category: "文档",
    demoUrl: "https://docs.yyc3.top/",
    liveUrl: "https://github.com/YYC-Cube/YYC3-AI-Family-Multi-Agent-Platform-",
  },
  {
    id: 10,
    title: "YYC³ AI Code",
    description: "FAmily AI Code - AI 辅助低代码开发平台，将设计直接转化为生产级代码",
    imageUrl: "/Project-Screenshot/YYC3-10.png",
    category: "开发工具",
    demoUrl: "https://code.yyc3.top/",
    liveUrl: "https://github.com/YYC-Cube/YYC3-AI-Code-FAmily",
  },
  // ===== 企业应用 =====
  {
    id: 11,
    title: "YYC³ Cloud Intelli-Matrix",
    description: "云智能矩阵平台，企业级智能应用管理与集成解决方案",
    imageUrl: "/Project-Screenshot/YYC3-11.png",
    category: "企业应用",
    demoUrl: "https://matrix.yyc3.top/",
    liveUrl: "https://github.com/YYC-Cube/YYC3-Cloud-Intelli-Matrix",
  },
  {
    id: 12,
    title: "YYC³ 言语Cloud 设计",
    description: "设计 UI 系统，统一的视觉规范、组件库与设计令牌管理",
    imageUrl: "/Project-Screenshot/YYC3-12.png",
    category: "创意设计",
    demoUrl: "https://design.yyc3.top/",
    liveUrl: "https://github.com/YYC-Cube/YYC3-UI-Design-System",
  },
  {
    id: 13,
    title: "YYC³ AI Intelligent Calling",
    description: "AI 智能呼叫系统，智能语音交互平台，自动化客户服务",
    imageUrl: "/Project-Screenshot/YYC3-13.png",
    category: "AI应用",
    demoUrl: "https://ai-call.yyc3.vip/",
    liveUrl: "https://github.com/YYC-Cube/YYC3-AI-Call",
  },
  {
    id: 14,
    title: "YYC³ Brain",
    description: "YYC³ Brain Computer System - 脑机接口系统，智能人机交互平台",
    imageUrl: "/Project-Screenshot/YYC3-14.png",
    category: "AI应用",
    demoUrl: "https://brain.yyc3.vip/",
    liveUrl: "https://github.com/YYC-Cube/YYC3-Brain-Compute-System",
  },
  {
    id: 15,
    title: "YYC³ 简易表格转换器",
    description: "YYC³ · 简易表格转换器，简洁高效的表格数据处理与格式转换工具",
    imageUrl: "/Project-Screenshot/YYC3-15.png",
    category: "工具应用",
    demoUrl: "https://table.yyc3.top/",
    liveUrl: "https://github.com/YYC-Cube/YYC3-Easy-Table-Converter",
  },
  {
    id: 16,
    title: "YYC³-Med",
    description: "AI-Powered Intelligent Medical System - 智能医疗系统，AI 辅助诊断与治疗",
    imageUrl: "/Project-Screenshot/YYC3-16.png",
    category: "行业解决方案",
    demoUrl: "https://medical.yyc3.vip/",
    liveUrl: "https://github.com/YYC-Cube/YYC3-Medical",
  },
  // ===== Web 应用 =====
  {
    id: 17,
    title: "YYC³ AI-Family 聊天机器人",
    description: "赛博朋克 DevOps 智能平台，AI 驱动的聊天机器人与自动化部署",
    imageUrl: "/Project-Screenshot/YYC3-17.png",
    category: "AI应用",
    demoUrl: "https://family-ai.yyc3.top/",
    liveUrl: "https://github.com/YYC-Cube/YYC3-AI-Family",
  },
  {
    id: 18,
    title: "YYC³ Pivot",
    description: "言启象限 · 语枢智云，数据中心与决策支持平台，智能数据分析",
    imageUrl: "/Project-Screenshot/YYC3-18.png",
    category: "Web应用",
    demoUrl: "https://pivot.yyc3.top/",
    liveUrl: "https://github.com/YYC-Cube/YYC3-CloudPivot-Intelli-Matrix",
  },
  {
    id: 19,
    title: "YYC³ Learning Platform",
    description: "AI 驱动的学习平台，个性化学习路径推荐与智能教学辅助",
    imageUrl: "/Project-Screenshot/YYC3-19.png",
    category: "教育科技",
    demoUrl: "https://learning-ai.yyc3.top/",
    liveUrl: "https://github.com/YYC-Cube/YYC3-Learning-Platform",
  },
  {
    id: 20,
    title: "YYC3 智慧商家管理系统",
    description: "Futuristic 智慧商家，数字化运营与管理，提升商业效率",
    imageUrl: "/Project-Screenshot/YYC3-20.png",
    category: "行业解决方案",
    demoUrl: "https://futuristic.yyc3.top/login/",
    liveUrl: "https://github.com/YYC-Cube/YYC3-Futuristic-Dashboard",
  },
  {
    id: 21,
    title: "言语云集成中心",
    description: "YYC³ Nexus - 言语云集成中心，智能应用展示与统一管理系统",
    imageUrl: "/Project-Screenshot/YYC3-21.png",
    category: "Web应用",
    demoUrl: "https://nexus.yyc3.vip/",
    liveUrl: "https://github.com/YYC-Cube/YYC3-Nexus",
  },
  {
    id: 22,
    title: "YYC³ AI Family 智能助手",
    description: "YYC³ AI Family - 赛博朋克 DevOps 智能平台，AI 驱动的聊天机器人",
    imageUrl: "/Project-Screenshot/YYC3-22.png",
    category: "AI应用",
    demoUrl: "https://ai-assis.yyc3.top/",
    liveUrl: "https://github.com/YYC-Cube/YYC3-Bot",
  },
  {
    id: 23,
    title: "YYC3 Gallery",
    description: "YYC3 Gallery Photography Template - 摄影作品展示平台，优雅的视觉呈现",
    imageUrl: "/Project-Screenshot/YYC3-23.png",
    category: "数字营销",
    demoUrl: "https://gallery.yyc3.top/",
    liveUrl: "https://github.com/YYC-Cube/YYC3-Infinite-Gallery",
  },
  {
    id: 24,
    title: "F-KTV POS 系统",
    description: "Club KTV 点歌与收银系统，娱乐行业智能化解决方案",
    imageUrl: "/Project-Screenshot/YYC3-24.png",
    category: "行业解决方案",
    demoUrl: "https://club.yyc3.top/rooms",
    liveUrl: "https://github.com/YYC-Cube/YYC3-Club-Ops",
  },
  {
    id: 25,
    title: "YYC³-QZ-Merchant-Management",
    description: "商家管理系统，智慧商家运营平台，数字化商业管理解决方案",
    imageUrl: "/Project-Screenshot/YYC3-25.png",
    category: "行业解决方案",
    demoUrl: "https://clube.yyc3.top/",
    liveUrl: "https://github.com/YYC-Cube/YYC3-QZ-Merchant-Management-System",
  },
  // ===== 企业应用（续） =====
  {
    id: 26,
    title: "YYC³ Nexus",
    description: "YYC³ Nexus - 言语云集成中心，企业级智能应用集成平台",
    imageUrl: "/Project-Screenshot/YYC3-26.png",
    category: "Web应用",
    demoUrl: "https://nexus.yyc3.top/",
    liveUrl: "https://github.com/YYC-Cube/YYC3-Nexus",
  },
  {
    id: 27,
    title: "YYC³ NexusAI",
    description: "YYC³ NexusAI - 智能中枢平台，AI 驱动的企业级应用集成与智能决策",
    imageUrl: "/Project-Screenshot/YYC3-27.png",
    category: "企业应用",
    demoUrl: "https://nexus-ai.yyc3.top/",
    liveUrl: "https://github.com/YYC-Cube/YYC3-Nexus-AI",
  },
  {
    id: 28,
    title: "YYC³ 万象归元",
    description: "YYC³ - 万象归元于云枢，深栈智启新纪元，企业级 SaaS 平台",
    imageUrl: "/Project-Screenshot/YYC3-28.png",
    category: "企业应用",
    demoUrl: "https://saas.yyc3.vip/",
    liveUrl: "https://github.com/YYC-Cube/YYC3-Saas-Landing",
  },
  {
    id: 29,
    title: "MusAI 缪斯智音",
    description: "MusAI 缪斯智音 - AI 音乐创作与智能音效生成平台，创意音乐助手",
    imageUrl: "/Project-Screenshot/YYC3-29.png",
    category: "创意设计",
    demoUrl: "https://d-music.yyc3.top/",
    liveUrl: "https://github.com/YYC-Cube/YYC3-D-MusAI",
  },
  {
    id: 30,
    title: "YYC³ Business Management",
    description: "YYC³ Business Management System - 商业管理系统，企业资源规划与流程优化",
    imageUrl: "/Project-Screenshot/YYC3-30.png",
    category: "企业应用",
    demoUrl: "https://management.yyc3.top/",
    liveUrl: "https://github.com/YYC-Cube/YYC3-Business-Management-System",
  },
  // ===== Web 应用（续） =====
  {
    id: 31,
    title: "YYC³ Portfolio",
    description: "YYC³ Portfolio — 言启象限 · 语枢未来，作品展示与项目管理平台",
    imageUrl: "/Project-Screenshot/YYC3-31.png",
    category: "数字营销",
    demoUrl: "https://protf.yyc3.top/",
    liveUrl: "https://github.com/YYC-Cube/YYC3-Portfolio",
  },
  {
    id: 32,
    title: "YYC³ AuraFlow",
    description: "YYC³ AuraFlow - AI 驱动的智能应用，流畅的用户体验与智能交互",
    imageUrl: "/Project-Screenshot/YYC3-32.png",
    category: "Web应用",
    demoUrl: "https://aureflow.yyc3.top/",
    liveUrl: "https://github.com/YYC-Cube/YYC3-Auraflow",
  },
  {
    id: 33,
    title: "YYC³ Portable Intelligent AI",
    description: "YYC³ Portable Intelligent AI System - 便携式智能 AI 系统，轻量级 AI 应用部署方案",
    imageUrl: "/Project-Screenshot/YYC3-33.png",
    category: "AI应用",
    demoUrl: "https://ai.yyc3.top/",
    liveUrl: "https://github.com/YYC-Cube/YYC3-AI-App-Intelligence-Platform",
  },
  {
    id: 34,
    title: "YYC³ Administration",
    description: "YYC³ Administration - YYC³ 管理后台，企业级权限与配置管理",
    imageUrl: "/Project-Screenshot/YYC3-34.png",
    category: "企业应用",
    demoUrl: "https://admin.yyc3.vip/",
    liveUrl: "https://github.com/YYC-Cube/YC3-Administration",
  },
  {
    id: 35,
    title: "YYC3 AI Family Pro",
    description: "YYC3 AI Family - Pro AI Family，专业版 AI 编程助手与多人协作平台",
    imageUrl: "/Project-Screenshot/YYC3-35.png",
    category: "AI应用",
    demoUrl: "https://pro.yyc3.top/",
    liveUrl: "https://github.com/YYC-Cube/YYC3-AI-Family-Multi-Agent-Platform-",
  },
  {
    id: 36,
    title: "YYC³ Customer Care Center",
    description: "YYC³ Customer Care Center | 言语云客户关怀中心，智能化客户服务与管理",
    imageUrl: "/Project-Screenshot/YYC3-36.png",
    category: "企业应用",
    demoUrl: "https://ccc.yyc3.top/",
    liveUrl: "https://github.com/YYC-Cube/YYC3-Customer-Care-Center",
  },
  {
    id: 37,
    title: "YYC³ Pulse",
    description: "YYC³ Pulse - 实时数据监控与 analytics 平台，智能运维与性能分析",
    imageUrl: "/Project-Screenshot/YYC3-37.png",
    category: "Web应用",
    demoUrl: "https://pulse.yyc3.top/zh-CN/",
    liveUrl: "https://github.com/YYC-Cube/YYC3-Pulse",
  },
];

export default projects;
